import { Injectable } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { NotificationsGateway } from '../notifications/notifications.gateway';

@Injectable()
export class ScheduledTasksService {
  constructor(
    private prisma: PrismaService,
    private notifications: NotificationsGateway,
  ) {}

  // Run every day at 11:30 PM to auto-generate daily reports
  @Cron('30 23 * * *')
  async autoGenerateDailyReports() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const branches = await this.prisma.branch.findMany({
      where: { isActive: true },
      include: {
        bankAccounts: { select: { id: true } },
      },
    });

    for (const branch of branches) {
      // Check if report already exists for today
      const existing = await this.prisma.dailyReport.findUnique({
        where: { branchId_date: { branchId: branch.id, date: today } },
      });
      if (existing) continue;

      const accountIds = branch.bankAccounts.map((a) => a.id);
      if (accountIds.length === 0) continue;

      // Calculate today's totals from actual transactions
      const todayStart = new Date(today);
      const todayEnd = new Date(today);
      todayEnd.setHours(23, 59, 59, 999);

      const transactions = await this.prisma.transaction.findMany({
        where: {
          createdAt: { gte: todayStart, lte: todayEnd },
          fromAccountId: { in: accountIds },
        },
      });

      let totalDeposit = 0;
      let totalWithdrawal = 0;
      for (const tx of transactions) {
        if (tx.type === 'DEPOSIT') {
          totalDeposit += Number(tx.amount);
        } else if (tx.type === 'WITHDRAWAL') {
          totalWithdrawal += Number(tx.amount);
        }
      }

      // Get total player balance (sum of all account balances)
      const accounts = await this.prisma.bankAccount.findMany({
        where: { branchId: branch.id },
        select: { bankBalance: true },
      });
      const playerBalance = accounts.reduce(
        (sum, a) => sum + Number(a.bankBalance),
        0,
      );

      // Only create if there were transactions
      if (totalDeposit > 0 || totalWithdrawal > 0) {
        // Get the first admin user for createdById
        const admin = await this.prisma.user.findFirst({
          where: { role: 'SUPER_ADMIN' },
        });
        if (!admin) continue;

        await this.prisma.dailyReport.create({
          data: {
            date: today,
            totalDeposit,
            totalWithdrawal,
            playerBalance,
            profitLoss: totalDeposit - totalWithdrawal,
            branchId: branch.id,
            createdById: admin.id,
          },
        });

        this.notifications.notifyGeneral({
          title: 'Auto Daily Report',
          message: `Daily report auto-generated for ${branch.name}`,
          type: 'info',
        });
      }
    }
  }
}
